### ISSUE TITLE
No module named `model.types_`

### ISSUE THREAD

**Issue by AADeLucia** [Cyn7hia/PAED#1]
Hi, when I run `python trainer_finetune.py` I run into the following module error:

```
Traceback (most recent call last):
    from model.VAESampler import MetaVAE
  File "C:\PycharmProjects\peacok_playground\PAED\model\VAESampler.py", line 9, in <module>
    from model.base import BaseVAE
  File "C:\PycharmProjects\peacok_playground\PAED\model\base.py", line 5, in <module>
    from model.types_ import *
ModuleNotFoundError: No module named 'model.types_'
```

Is there a missing `types` file in the repo which consolidates the used datatypes? I also see this line in VAESampler.py.

Thanks.

**Comment by Cyn7hia** [comment]
Hi,

I uploaded the types_.py in the repo. Thanks for your suggestions!

> Hi, when I run `python trainer_finetune.py` I run into the following module error:
> 
> ```
> Traceback (most recent call last):
>     from model.VAESampler import MetaVAE
>   File "C:\PycharmProjects\peacok_playground\PAED\model\VAESampler.py", line 9, in <module>
>     from model.base import BaseVAE
>   File "C:\PycharmProjects\peacok_playground\PAED\model\base.py", line 5, in <module>
>     from model.types_ import *
> ModuleNotFoundError: No module named 'model.types_'
> ```
> 
> Is there a missing `types` file in the repo which consolidates the used datatypes? I also see this line in VAESampler.py.
> 
> Thanks.

**Comment by AADeLucia** [comment]
Thanks!
