### ISSUE TITLE
ModuleNotFoundError: No module named `knowledge_prepare`

### ISSUE THREAD

**Issue by AADeLucia** [Cyn7hia/PAED#2]
In `wrapper.py` there is a reference to `from knowledge_prepare import load_u2t`, but `knowledge_prepare` is not in the repo and I could not find it elsewhere.

Thanks.

**Comment by Cyn7hia** [comment]
> In `wrapper.py` there is a reference to `from knowledge_prepare import load_u2t`, but `knowledge_prepare` is not in the repo and I could not find it elsewhere.
> 
> Thanks.

Thanks! I updated the `load_u2t` in `utils.py` and also the `wrapper.py` with changes from `from knowledge_prepare import load_u2t` to `from utils import load_u2t`.

**Comment by AADeLucia** [comment]
Thanks!
